# Generated by Django 4.2.4 on 2023-09-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0002_pedido_producto_foto_producto_marca_producto_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to='productos/'),
        ),
    ]
